// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAeec74c4DecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(in *jlexer.Lexer, out *KafkaNotificationMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "user_uid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserUID = string(in.String())
			}
		case "notification":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Notification).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAeec74c4EncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(out *jwriter.Writer, in KafkaNotificationMessage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user_uid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserUID))
	}
	{
		const prefix string = ",\"notification\":"
		out.RawString(prefix)
		(in.Notification).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KafkaNotificationMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAeec74c4EncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KafkaNotificationMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAeec74c4EncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KafkaNotificationMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAeec74c4DecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KafkaNotificationMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAeec74c4DecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(l, v)
}
