// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson45c7fc81DecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(in *jlexer.Lexer, out *StoredSubscription) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "endpoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Endpoint = string(in.String())
			}
		case "p256dh":
			if in.IsNull() {
				in.Skip()
			} else {
				out.P256dh = string(in.String())
			}
		case "auth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Auth = string(in.String())
			}
		case "created_at":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.CreatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson45c7fc81EncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(out *jwriter.Writer, in StoredSubscription) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"endpoint\":"
		out.RawString(prefix[1:])
		out.String(string(in.Endpoint))
	}
	{
		const prefix string = ",\"p256dh\":"
		out.RawString(prefix)
		out.String(string(in.P256dh))
	}
	{
		const prefix string = ",\"auth\":"
		out.RawString(prefix)
		out.String(string(in.Auth))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StoredSubscription) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson45c7fc81EncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StoredSubscription) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson45c7fc81EncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StoredSubscription) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson45c7fc81DecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StoredSubscription) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson45c7fc81DecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(l, v)
}
