// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF7ff6efeDecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(in *jlexer.Lexer, out *SubscriptionReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "endpoint":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Endpoint = string(in.String())
			}
		case "keys":
			easyjsonF7ff6efeDecode(in, &out.Keys)
		case "user_agent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserAgent = string(in.String())
			}
		case "device_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DeviceID = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF7ff6efeEncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(out *jwriter.Writer, in SubscriptionReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"endpoint\":"
		out.RawString(prefix[1:])
		out.String(string(in.Endpoint))
	}
	{
		const prefix string = ",\"keys\":"
		out.RawString(prefix)
		easyjsonF7ff6efeEncode(out, in.Keys)
	}
	if in.UserAgent != "" {
		const prefix string = ",\"user_agent\":"
		out.RawString(prefix)
		out.String(string(in.UserAgent))
	}
	if in.DeviceID != "" {
		const prefix string = ",\"device_id\":"
		out.RawString(prefix)
		out.String(string(in.DeviceID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SubscriptionReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF7ff6efeEncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SubscriptionReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF7ff6efeEncodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SubscriptionReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF7ff6efeDecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SubscriptionReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF7ff6efeDecodeGithubComCg2025CrutchBackendNotificationServiceInternalModels(l, v)
}
func easyjsonF7ff6efeDecode(in *jlexer.Lexer, out *struct {
	P256dh string `json:"p256dh"`
	Auth   string `json:"auth"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "p256dh":
			if in.IsNull() {
				in.Skip()
			} else {
				out.P256dh = string(in.String())
			}
		case "auth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Auth = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF7ff6efeEncode(out *jwriter.Writer, in struct {
	P256dh string `json:"p256dh"`
	Auth   string `json:"auth"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"p256dh\":"
		out.RawString(prefix[1:])
		out.String(string(in.P256dh))
	}
	{
		const prefix string = ",\"auth\":"
		out.RawString(prefix)
		out.String(string(in.Auth))
	}
	out.RawByte('}')
}
